<ADSWorkspace Revision="30" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="Simulation_Sequencing" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="RF_Double_Stage_Amplifier_lib" />
        <Folder Name="Emilie">
            <Cell Name="RF_Double_Stage_Amplifier_lib:static network" />
            <Data_Display Name="static network.dds" />
            <Folder Name="legacy">
                <Cell Name="RF_Double_Stage_Amplifier_lib:double_stage" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:in_out_impedance" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Proto" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:proto_stab" />
                <Data_Display Name="in_out_impedance.dds" />
                <Data_Display Name="Proto.dds" />
                <Data_Display Name="double_stage.dds" />
            </Folder>
            <Folder Name="Impedance Matching">
                <Data_Display Name="Impedance Matching Cascade.dds" />
                <Data_Display Name="Impedance Matching Cascade Synthesis.dds" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade Synthesis" />
                <Data_Display Name="Impedance Matching Cascade Optim.dds" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade Optim" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch2_Impedance_Matching_Cascade_Synthesis" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch1_Impedance_Matching_Cascade_Synthesis" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch_Impedance_Matching_Cascade_Synthesis" />
            </Folder>
            <Folder Name="Transmission Line">
                <Cell Name="RF_Double_Stage_Amplifier_lib:Cascade with Transmission Line" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Cascade with Transmission Line Partial" />
                <Data_Display Name="Cascade with Transmission Line.dds" />
                <Data_Display Name="Cascade with Transmission Line Partial.dds" />
            </Folder>
        </Folder>
        <Folder Name="Maxime">
            <Cell Name="RF_Double_Stage_Amplifier_lib:cell_1" />
        </Folder>
        <Folder Name="Main" />
        <Library Name="test_model_ce3512k2_lib" />
        <Log Name="netlist.log" />
        <Dataset Name="Proto.ds" />
        <Data_Files Name="Proto.ds" />
        <Log Name="search_history.log" />
        <ConfigFile Name="dds.cfg" />
        <Dataset Name="static_network.ds" />
        <Data_Files Name="static_network.ds" />
        <Dataset Name="in_out_impedance.ds" />
        <Data_Files Name="in_out_impedance.ds" />
        <Dataset Name="in_out_impedance_vds_sweep.ds" />
        <Data_Files Name="in_out_impedance_vds_sweep.ds" />
        <Dataset Name="in_out_impedance_vgs_sweep.ds" />
        <Data_Files Name="in_out_impedance_vgs_sweep.ds" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Preferences Name="RF_Double_Stage_Amplifier_lib_lay.prf" />
        <Preferences Name="test_model_ce3512k2_lib_lay.prf" />
        <Dataset Name="double_stage.ds" />
        <Data_Files Name="double_stage.ds" />
        <Dataset Name="Impedance_Matching_Cascade.ds" />
        <Data_Files Name="Impedance_Matching_Cascade.ds" />
        <Dataset Name="Impedance_Matching_Cascade_Synthesis.ds" />
        <Data_Files Name="Impedance_Matching_Cascade_Synthesis.ds" />
        <ConfigFile Name="linecalc.cfg" />
        <Preferences Name="RF_Double_Stage_Amplifier_lib_sch.prf" />
        <Dataset Name="__simdata117360.ds" />
        <Dataset Name="Cascade_with_Transmission_Line.ds" />
        <Data_Files Name="Cascade_with_Transmission_Line.ds" />
        <Data_Files Name="__simdata117360.ds" />
        <Data_Files Name="Cascade_with_Transmission_Line_data\logFile.txt" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Synthesis_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Synthesis_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Proto_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Proto_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_double_stage_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_double_stage_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_in_out_impedance_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_in_out_impedance_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_static#20network_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_static#20network_schematic\annotation_map.xml" />
        <Data_Files Name="double_stage_data\logFile.txt" />
        <Data_Files Name="Impedance_Matching_Cascade_data\logFile.txt" />
        <Data_Files Name="Impedance_Matching_Cascade_Optim_data\logFile.txt" />
        <Data_Files Name="Impedance_Matching_Cascade_Synthesis_data\logFile.txt" />
        <Data_Files Name="in_out_impedance_data\logFile.txt" />
        <Data_Files Name="in_out_impedance_vds_sweep_data\logFile.txt" />
        <Data_Files Name="in_out_impedance_vgs_sweep_data\logFile.txt" />
        <Data_Files Name="Proto_data\logFile.txt" />
        <Data_Files Name="static_network_data\logFile.txt" />
        <Library Name="ads_quantum" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line_schematic_\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line_schematic_\annotation_map.xml" />
        <Dataset Name="__simdata045118.ds" />
        <Dataset Name="__simdata073934.ds" />
        <Data_Files Name="__simdata045118.ds" />
        <Data_Files Name="__simdata073934.ds" />
        <Substrate Name="test_model_ce3512k2_lib:teflon_762um.subst" />
        <Cell Name="test_model_ce3512k2_lib:CEL_CE3512K2_modele" />
        <Cell Name="test_model_ce3512k2_lib:pad_trasistor" />
        <Data_Files Name="Cascade_with_Transmission_Line_Partial_data\logFile.txt" />
        <Data_Files Name="Cascade_with_Transmission_Line_Partial.ds" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line#20%Partial_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line#20%Partial_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line#20%Partial_schematic_\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line#20%Partial_schematic_\annotation_map.xml" />
        <Dataset Name="Impedance_Matching_Cascade_Optim.ds" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim_schematic_\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim_schematic_\annotation_map.xml" />
    </Workspace>
</ADSWorkspace>
