<ADSWorkspace Revision="40" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="Simulation_Sequencing" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="RF_Double_Stage_Amplifier_lib" />
        <Folder Name="Emilie">
            <Cell Name="RF_Double_Stage_Amplifier_lib:static network" />
            <Data_Display Name="static network.dds" />
            <Folder Name="legacy">
                <Cell Name="RF_Double_Stage_Amplifier_lib:double_stage" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:in_out_impedance" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Proto" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:proto_stab" />
                <Data_Display Name="in_out_impedance.dds" />
                <Data_Display Name="Proto.dds" />
                <Data_Display Name="double_stage.dds" />
            </Folder>
            <Folder Name="Impedance Matching">
                <Data_Display Name="Impedance Matching Cascade.dds" />
                <Data_Display Name="Impedance Matching Cascade Synthesis.dds" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade Synthesis" />
                <Data_Display Name="Impedance Matching Cascade Optim.dds" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade Optim" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch2_Impedance_Matching_Cascade_Synthesis" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch1_Impedance_Matching_Cascade_Synthesis" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch_Impedance_Matching_Cascade_Synthesis" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade Optim Inter" />
                <Data_Display Name="Impedance Matching Cascade Optim Inter.dds" />
            </Folder>
            <Folder Name="Transmission Line">
                <Cell Name="RF_Double_Stage_Amplifier_lib:Cascade with Transmission Line" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Cascade with Transmission Line Partial" />
                <Data_Display Name="Cascade with Transmission Line.dds" />
                <Data_Display Name="Cascade with Transmission Line Partial.dds" />
                <Cell Name="RF_Double_Stage_Amplifier_lib:Cascade with Transmission Line Inter" />
                <Data_Display Name="Cascade with Transmission Line Inter.dds" />
            </Folder>
            <Cell Name="RF_Double_Stage_Amplifier_lib:polar_in" />
            <Folder Name="Real Comp">
                <Cell Name="RF_Double_Stage_Amplifier_lib:Real Comp cap" />
            </Folder>
            <Substrate Name="test_model_ce3512k2_lib:teflon_762um_v1.subst" />
            <Substrate Name="RF_Double_Stage_Amplifier_lib:teflon_762um_v2.subst" />
        </Folder>
        <Folder Name="Maxime">
            <Cell Name="RF_Double_Stage_Amplifier_lib:cell_1" />
        </Folder>
        <Folder Name="Main" />
        <Library Name="test_model_ce3512k2_lib" />
        <Log Name="netlist.log" />
        <Dataset Name="Proto.ds" />
        <Data_Files Name="Proto.ds" />
        <Log Name="search_history.log" />
        <ConfigFile Name="dds.cfg" />
        <Dataset Name="static_network.ds" />
        <Data_Files Name="static_network.ds" />
        <Dataset Name="in_out_impedance.ds" />
        <Data_Files Name="in_out_impedance.ds" />
        <Dataset Name="in_out_impedance_vds_sweep.ds" />
        <Data_Files Name="in_out_impedance_vds_sweep.ds" />
        <Dataset Name="in_out_impedance_vgs_sweep.ds" />
        <Data_Files Name="in_out_impedance_vgs_sweep.ds" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Preferences Name="RF_Double_Stage_Amplifier_lib_lay.prf" />
        <Preferences Name="test_model_ce3512k2_lib_lay.prf" />
        <Dataset Name="double_stage.ds" />
        <Data_Files Name="double_stage.ds" />
        <Dataset Name="Impedance_Matching_Cascade.ds" />
        <Data_Files Name="Impedance_Matching_Cascade.ds" />
        <Dataset Name="Impedance_Matching_Cascade_Synthesis.ds" />
        <Data_Files Name="Impedance_Matching_Cascade_Synthesis.ds" />
        <ConfigFile Name="linecalc.cfg" />
        <Preferences Name="RF_Double_Stage_Amplifier_lib_sch.prf" />
        <Dataset Name="__simdata117360.ds" />
        <Dataset Name="Cascade_with_Transmission_Line.ds" />
        <Data_Files Name="Cascade_with_Transmission_Line.ds" />
        <Data_Files Name="__simdata117360.ds" />
        <Dataset Name="__simdata045118.ds" />
        <Dataset Name="__simdata073934.ds" />
        <Data_Files Name="__simdata045118.ds" />
        <Data_Files Name="__simdata073934.ds" />
        <Dataset Name="Impedance_Matching_Cascade_Optim.ds" />
        <Dataset Name="__simdata064441.ds" />
        <Dataset Name="__simdata074071.ds" />
        <Dataset Name="__simdata129084.ds" />
        <Dataset Name="__simdata130392.ds" />
        <Data_Files Name="__simdata129084.ds" />
        <Data_Files Name="__simdata074071.ds" />
        <Data_Files Name="__simdata130392.ds" />
        <Data_Files Name="__simdata064441.ds" />
        <Dataset Name="Impedance_Matching_Cascade_Optim_Inter.ds" />
        <Data_Files Name="Impedance_Matching_Cascade_Optim_Inter.ds" />
        <Dataset Name="__simdata089476.ds" />
        <Dataset Name="Cascade_with_Transmission_Line_Inter.ds" />
        <Data_Files Name="Cascade_with_Transmission_Line_Inter.ds" />
        <Data_Files Name="__simdata089476.ds" />
        <Dataset Name="Impedance_Matching_Cascade_Inter_Synthesis.ds" />
        <Data_Files Name="Impedance_Matching_Cascade_Inter_Synthesis.ds" />
        <Data_Display Name="Impedance Matching Cascade Inter Synthesis.dds" />
        <Data_Display Name="Impedance Matching Cascade Inter Opti.dds" />
        <Dataset Name="Impedance_Matching_Cascade_Inter_Opti.ds" />
        <Dataset Name="Cascade_with_Transmission_Line_Partial.ds" />
        <Preferences Name="ads_rflib_lay.prf" />
        <Dataset Name="polar_in.ds" />
        <Data_Files Name="in_out_impedance_data/logFile.txt" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim_schematic_/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim_schematic_/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_in_out_impedance_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_in_out_impedance_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line#20%Partial_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line#20%Partial_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim#20%Inter_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Optim#20%Inter_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_double_stage_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_double_stage_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Proto_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Proto_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_static#20network_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_static#20network_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line#20%Inter_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Cascade#20with#20%Transmission#20%Line#20%Inter_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Inter#20%Synthesis_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Inter#20%Synthesis_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Synthesis_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Synthesis_schematic/annotation_map.xml" />
        <Data_Files Name="Impedance_Matching_Cascade_Inter_Opti_data/logFile.txt" />
        <Data_Files Name="Cascade_with_Transmission_Line_data/logFile.txt" />
        <Data_Files Name="Impedance_Matching_Cascade_data/logFile.txt" />
        <Data_Files Name="Proto_data/logFile.txt" />
        <Data_Files Name="Impedance_Matching_Cascade_Optim_data/logFile.txt" />
        <Data_Files Name="static_network_data/logFile.txt" />
        <Data_Files Name="double_stage_data/logFile.txt" />
        <Data_Files Name="polar_in.ds" />
        <Data_Files Name="Impedance_Matching_Cascade_Optim_Inter_data/logFile.txt" />
        <Data_Files Name="Impedance_Matching_Cascade_Synthesis_data/logFile.txt" />
        <Data_Files Name="Cascade_with_Transmission_Line_Inter_data/logFile.txt" />
        <Data_Files Name="Impedance_Matching_Cascade_Inter_Synthesis_data/logFile.txt" />
        <Data_Files Name="polar_in_data/logFile.txt" />
        <Data_Files Name="Cascade_with_Transmission_Line_Partial_data/logFile.txt" />
        <Data_Files Name="in_out_impedance_vds_sweep_data/logFile.txt" />
        <Data_Files Name="in_out_impedance_vgs_sweep_data/logFile.txt" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Inter#20%Opti_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Inter#20%Opti_schematic/annotation_map.xml" />
        <Data_Display Name="Impedance Matching Cascade Inter Synthesis 2.dds" />
        <Dataset Name="__simdata023099.ds" />
        <Dataset Name="__simdata079502.ds" />
        <Dataset Name="__simdata107060.ds" />
        <Dataset Name="__simdata108880.ds" />
        <Data_Files Name="DA_LCBandpassMatch1_Impedance Matching Cascade Inter Synthesis 2_Load.s1p" />
        <Data_Files Name="__simdata079502.ds" />
        <Data_Files Name="__simdata107060.ds" />
        <Data_Files Name="__simdata108880.ds" />
        <Data_Files Name="__simdata023099.ds" />
        <Data_Files Name="Impedance_Matching_Cascade_Inter_Synthesis_2_data/logFile.txt" />
        <Dataset Name="Impedance_Matching_Cascade_Inter_Synthesis_2.ds" />
        <Dataset Name="__simdata113451.ds" />
        <Data_Files Name="__simdata113451.ds" />
        <Dataset Name="__simdata029158.ds" />
        <Data_Files Name="__simdata029158.ds" />
        <Dataset Name="__simdata103791.ds" />
        <Data_Files Name="__simdata103791.ds" />
        <Dataset Name="__simdata048760.ds" />
        <Data_Files Name="__simdata048760.ds" />
        <Dataset Name="__simdata013094.ds" />
        <Data_Files Name="__simdata013094.ds" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Inter#20%Synthesis#202_schematic_/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Inter#20%Synthesis#202_schematic_/annotation_map.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Inter#20%Synthesis#202_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Impedance#20%Matching#20%Cascade#20%Inter#20%Synthesis#202_schematic/annotation_map.xml" />
        <Data_Display Name="Real Comp cap.dds" />
        <Dataset Name="__simdata001908.ds" />
        <Dataset Name="__simdata005121.ds" />
        <Dataset Name="__simdata017133.ds" />
        <Dataset Name="__simdata033763.ds" />
        <Dataset Name="__simdata116455.ds" />
        <Dataset Name="Real_Comp_cap.ds" />
        <Data_Files Name="__simdata005121.ds" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Real#20%Comp#20cap_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Real#20%Comp#20cap_schematic/annotation_map.xml" />
        <Data_Files Name="__simdata001908.ds" />
        <Data_Files Name="Real_Comp_cap_data/logFile.txt" />
        <Data_Files Name="__simdata017133.ds" />
        <Data_Files Name="Real_Comp_cap.ds" />
        <Data_Files Name="__simdata033763.ds" />
        <Data_Files Name="Real_Comp_cap_2_data/logFile.txt" />
        <Data_Files Name="__simdata116455.ds" />
        <Dataset Name="Real_Comp_cap_2.ds" />
        <Data_Files Name="Real_Comp_cap_2.ds" />
        <Data_Display Name="Real Comp cap 2.dds" />
        <Library Name="JTI_CAPS_S_Series" />
        <LibDM Name="JTI_CAPS_S_Series:data.dm" />
        <Library Name="JTI0603WirewoundIND_2011" />
        <Dataset Name="__simdata094726.ds" />
        <Data_Files Name="__simdata094726.ds" />
        <Dataset Name="__simdata038297.ds" />
        <Data_Files Name="__simdata038297.ds" />
        <Dataset Name="__simdata124085.ds" />
        <Data_Files Name="__simdata124085.ds" />
        <Dataset Name="__simdata014711.ds" />
        <Data_Files Name="__simdata014711.ds" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Real#20%Comp#20cap#202_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/%R%F_%Double_%Stage_%Amplifier_lib_%Real#20%Comp#20cap#202_schematic/annotation_map.xml" />
        <Dataset Name="__simdata118141.ds" />
        <Data_Files Name="__simdata118141.ds" />
        <Preferences Name="ads_sources_lay.prf" />
        <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch1_Impedance_Matching_Cascade_Inter_Synthesis_2" />
        <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch2_Impedance_Matching_Cascade_Inter_Synthesis_2" />
        <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch_Impedance_Matching_Cascade_Inter_Synthesis" />
        <Cell Name="RF_Double_Stage_Amplifier_lib:DA_LCBandpassMatch_Impedance_Matching_Cascade_Inter_Synthesis_2" />
        <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade Inter Opti" />
        <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade Inter Synthesis" />
        <Cell Name="RF_Double_Stage_Amplifier_lib:Impedance Matching Cascade Inter Synthesis 2" />
        <Cell Name="RF_Double_Stage_Amplifier_lib:Real Comp cap 2" />
        <Substrate Name="test_model_ce3512k2_lib:teflon_762um.subst" />
        <Cell Name="test_model_ce3512k2_lib:CEL_CE3512K2_modele" />
        <Cell Name="test_model_ce3512k2_lib:pad_trasistor" />
        <LibDM Name="JTI_CAPS_S_Series:data.dm" />
    </Workspace>
</ADSWorkspace>
